apps/authenticate/urls.py
from django.urls import path
from .views import *


app_name = 'authenticate'

urlpatterns = [
    path('index/', index, name="index"),
    path('register/', register, name="register"),
    path('user_login/', login_user, name="login_user"),
    path('validate/',validate_auth, name="validate_login"),
    path('logout/', user_logout, name="logout_user"),
    path('export_pdf/', export_pdf, name="export_pdf")
]

logintest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler400, handler403, handler404, handler500
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authenticate/', include('apps.authenticate.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = myErrors.erro400

apps/authenticate/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    date_birth = models.DateField(auto_now=False, auto_now_add=False)
    profile_image = models.ImageField(upload_to='profile_images',blank=True)

    class Meta:
        permissions = (
            ("download_pdf", "Puede descargar PDF"),
            ("permiso_1", "Custom Permiso 1"),
            ("permiso_2", "Custom Permiso 2"),
            ("permiso_3", "Custom Permiso 3"),
            ("permiso_4", "Custom Permiso 4"),
        )
    
    def __str__(self):
        return self.user.username

    def showMyProfilePicture(self):
        return self.profile_image.url

apps/authenticate/forms.py
from django import forms
from .models import UserProfileInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={ 'placeholder': 'Password'}))
    confirm_password=forms.CharField(widget=forms.PasswordInput(attrs={ 'placeholder': 'Repita su password'}))

    class Meta():
        model = User
        fields = ('username','password','email', 'first_name')
        widgets = {
            'first_name': forms.TextInput(
                attrs={'placeholder': 'Nombre'}),
            'username': forms.TextInput(
                attrs={'placeholder': 'Username'}),
            'email': forms.EmailInput(
                attrs={'placeholder': 'Email'}),
        }
    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
          self.add_error('confirm_password', "Su contraseña no coincide")


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
      model = UserProfileInfo
      fields = ('date_birth','profile_image')
      widgets = {
        'date_birth': forms.DateInput(attrs={'placeholder':'Fecha nacimiento', 'id':'datetimepicker1'})
      }

class LoginForm(forms.Form):

  username = forms.CharField(max_length=50, widget=forms.TextInput(attrs={
      'type': 'text',
      'placeholder': 'Nombre de usuario',
    }))
  password = forms.CharField(max_length=50, widget=forms.TextInput(attrs={
      'type': 'password',
      'placeholder': 'Password'
    }))

  def clean(self):
    user_found = User.objects.filter(username = self.cleaned_data['username']).exists()
    if not user_found:
      self.add_error('username', 'Username y/o password no encontrados')
    else:
      user = User.objects.get(username = self.cleaned_data['username'])
      if not user.check_password(self.cleaned_data['password']):
        self.add_error('username', 'Password incorrecto')

apps/authenticate/views.py
from django.shortcuts import render, redirect
from .forms import UserForm,UserProfileInfoForm, LoginForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required#, permission_required
from .decorators.extensions import permission_required
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from django.http import FileResponse
import io
# Create your views here.

def index(request):
    context = {'download_pdf': request.user.has_perm("authenticate.download_pdf")}
    print(request.user.has_perm("authenticate.download_pdf"))
    return render(request,'index.html', context)

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_image' in request.FILES:
                profile.profile_image = request.FILES['profile_image']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

def login_user(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        username = request.POST.get('username')
        password = request.POST.get('password')
        nextPage = request.POST.get('next')
        if form.is_valid():
            user = authenticate(username=username, password=password)
            if user is not None and user.is_active:
                login(request,user)
                request.session['myUserName'] = user.username
                request.session['myProfilePicture'] = user.userprofileinfo.showMyProfilePicture()
                if nextPage:
                    return redirect(nextPage)
                else:
                    return redirect("authenticate:index")
            else:
                return HttpResponse("Your account was inactive.")
    else:
        form = LoginForm
    return render(request, 'login.html', {'form':form})

@login_required
def validate_auth(request):
    return render(request, 'validate.html', {'message':"Solo los verdaderos profetas autenticados veran este mensaje !"})

@login_required
@permission_required(['authenticate.download_pdf'])
def export_pdf(request):
    c = canvas.Canvas("grilla-alumnos.pdf", pagesize=A4)
    w, h = A4
    max_rows_per_page = 45
    # Margin.
    x_offset = 50
    y_offset = 50
    # Space between rows.
    padding = 15
    
    xlist = [x + x_offset for x in [0, 200, 250, 300, 350, 400, 480]]
    ylist = [h - y_offset - i*padding for i in range(max_rows_per_page + 1)]
    
    for rows in range(1,100):
        rows = tuple(filter(bool, rows))
        c.grid(xlist, ylist[:len(rows) + 1])
        for y, row in zip(ylist[:-1], rows):
            for x, cell in zip(xlist, row):
                c.drawString(x + 2, y - padding + 3, str(cell))
        c.showPage()
    
    c.save()
    data = [("NOMBRE", "NOTA 1", "NOTA 2", "NOTA 3", "PROM.", "ESTADO")]
    for i in range(1, 101):
        exams = [randint(0, 10) for _ in range(3)]
        avg = round(mean(exams), 2)
        state = "Aprobado" if avg >= 4 else "Desaprobado"
        data.append((f"Alumno {i}", *exams, avg, state))
    export_to_pdf(data)

@login_required
def user_logout(request):
    logout(request)
    return redirect("authenticate:index")

    

apps/authenticate/templates/base.html
<!DOCTYPE html>
{% load static %}
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}{% endblock title %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <link rel="stylesheet" href="{% static 'fonts/material-icon/css/material-design-iconic-font.min.css' %}">
        {% load bootstrap4 %}
    
        {# CSS Bootstrap #}
        {% bootstrap_css %}

        {% block styles %}
        {% endblock styles %}
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        {% block content %}
        {% endblock content %}
        {% bootstrap_javascript jquery='full' %}
        {% block scripts %}
        {% endblock scripts %}
    </body>
</html>

apps/authenticate/templates/index.html
{% extends "base.html" %}

{% block content %}
    <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
      <a class="navbar-brand" href="#">Start Bootstrap</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="#">Home</a>
          </li>
            {% if user.is_authenticated %}
                <li class="nav-item"> 
                  <span class="nav-link">Hola, {{ user.username }}</span>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'authenticate:logout_user' %}">Cerrar Sesion</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'authenticate:register' %}">Registrar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'authenticate:login_user' %}">Iniciar sesión</a>
                </li>
            {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h1 class="mt-5">Welcome to Login</h1>
        {% if user.is_authenticated %}
          <img src="{{ request.session.myProfilePicture }}" width="100">
        {% endif %}
        {% if download_pdf %}
          <br>
          <a href="{% url 'authenticate:export_pdf' %}">Download</a>
        {% endif %}
        <p class="lead">By Yeison Suarez</p>
      </div>
    </div>
  </div>
{% endblock content %}

apps/authenticate/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block styles %}
    <link rel="stylesheet" href="{% static '/css/style.css' %}"/>
{% endblock styles %}
{% block content %}
    <div class="container mt-5">
        <!-- Sing in  Form -->
        <section class="sign-in">
            <div class="container">
                <div class="row">
                    <div class="col-10 offset-1 mt-5">
                        {% if form.errors %}
                            <div class="alert alert-danger">
                                <button type="button" class="close" data-dismiss="alert">×</button>
                                {% for field in form %}
                                    {% if field.errors %}
                                    <li>{{ field.errors|striptags }}</li>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                </div>
                <div class="signin-content">
                    <div class="signin-image">
                        <figure><img src="{% static 'images/signin-image.jpg' %}" alt="login image"></figure>
                        <a href="{% url 'authenticate:register' %}" class="signup-image-link">Create an account</a>
                    </div>

                    <div class="signin-form">
                        <h2 class="form-title">Login</h2>
                        <form method="POST" class="register-form" id="login-form">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="username"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                {{ form.username }}
                            </div>
                            <div class="form-group">
                                <label for="password"><i class="zmdi zmdi-lock"></i></label>
                                {{ form.password }}
                            </div>
                            <input type="hidden" name="next" value="{{ request.GET.next }}"/>
                            <div class="form-group form-button">
                                <button type="submit" name="btnEnviado" value="Hola mundo" class="form-submit">Log in</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock content %}

apps/authenticate/templates/registration.html
{% extends 'base.html' %}
{% load static %}
{% block styles %}
    <link rel="stylesheet" href="{% static '/css/style.css' %}"/>          
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css"> {# Adds date-picker required JS and CSS #}
{% endblock styles %}
{% block content %}
    <div class="main">
        <!-- Sign up form -->
        <section class="">
            <div class="container">
                {% if user_form.errors or profile_form.errors %}
                    <div class="alert alert-danger">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        {% for field in user_form %}
                            {% if field.errors %}
                            <li>{{ field.label}}: {{ field.errors|striptags }}</li>
                            {% endif %}
                        {% endfor %}
                        {% for field in profile_form %}
                            {% if field.errors %}
                            <li>{{ field.label}}:{{ field.errors|striptags }}</li>
                            {% endif %}
                        {% endfor %}
                    </div>
                {% endif %}
                {% if registered %}
                    <div class="alert alert-success">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <span>Usuario registrado con exito <a href="{% url 'authenticate:login_user' %}">Ir a login</a></span>
                    </div>
                {% endif %}
            </div>
            <div class="container">
                <div class="signup-content">
                    <div class="signup-form">
                        <h2 class="form-title">Sign up</h2>
                        <form method="POST" class="register-form" id="register-form" enctype="multipart/form-data" novalidate>
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="username"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                {{ user_form.first_name }}
                            </div>
                            <div class="form-group">
                                <label for="username"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                {{ user_form.username }}
                            </div>
                            <div class="form-group">
                                <label for="email"><i class="zmdi zmdi-email"></i></label>
                                {{ user_form.email }}
                            </div>
                            <div class="form-group">
                                <label for="date_birth"><i class="zmdi zmdi-calendar"></i></label>
                                {{ profile_form.date_birth }}
                            </div>
                            <div class="form-group">
                                <label for="profile_image"><i class="zmdi zmdi-image"></i></label>
                                {{ profile_form.profile_image }}
                            </div>
                            <div class="form-group">
                                <label for="password"><i class="zmdi zmdi-lock"></i></label>
                                {{ user_form.password }}
                            </div>
                            <div class="form-group">
                                <label for="confirm_password"><i class="zmdi zmdi-lock-outline"></i></label>
                                {{ user_form.confirm_password }}
                            </div>
                            <div class="form-group form-button">
                                <input type="submit" name="signup" id="signup" class="form-submit" value="Register"/>
                            </div>
                        </form>
                    </div>
                    <div class="signup-image">
                        <figure><img src="{% static 'images/signup-image.jpg' %}" alt="sing up image"></figure>
                        <a href="{% url 'authenticate:login_user' %}" class="signup-image-link">Soy usuario registrado</a>
                    </div>
                </div>
            </div>
        </section>
    </div>
    
{% endblock content %}
{% block scripts %}
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $.datepicker.regional['es'] = {
            closeText: 'Cerrar',
            prevText: '< Ant',
            nextText: 'Sig >',
            currentText: 'Hoy',
            monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
            monthNamesShort: ['Ene','Feb','Mar','Abr', 'May','Jun','Jul','Ago','Sep', 'Oct','Nov','Dic'],
            dayNames: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
            dayNamesShort: ['Dom','Lun','Mar','Mié','Juv','Vie','Sáb'],
            dayNamesMin: ['Do','Lu','Ma','Mi','Ju','Vi','Sá'],
            weekHeader: 'Sm',
            dateFormat: 'yy-mm-dd',
            firstDay: 1,
            isRTL: false,
            showMonthAfterYear: false,
            yearSuffix: ''
            };
            $.datepicker.setDefaults($.datepicker.regional['es']);
            $('#datetimepicker1').datepicker();
        });
    </script>
{% endblock scripts %}

apps/authenticate/templates/validate.html
{% extends "base.html" %}
{% block content %}
    {{message}}
    <br/>
    <a href="{% url 'authenticate:index' %}">Inicio</a>
    <br/>
    <a href="{% url 'authenticate:logout_user' %}">Cerrar sesion</a>
{% endblock content %}